"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeftRight, ArrowRight, CalendarDays, Check, ChevronDown, ChevronRight, Clock3, CreditCard, Info, MapPin, Menu, Minus, Plus, Search, Ticket, TrainFront, X } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

type Train = { id:string; name:string; kind:string; from:string; to:string; depart:string; arrive:string; minutes:number; stops:number; price:number; platform:string; accent:string };
type Booking = { code:string; train:Train; date:string; passengers:number; seatClass:string; name:string; email:string; seat:string; status:"Đã xác nhận"|"Đã hủy" };
const stations=["Tokyo","Shinagawa","Shin-Yokohama","Nagoya","Kyoto","Shin-Osaka","Hiroshima","Hakata","Sendai","Kanazawa"];
const trains:Train[]=[
  {id:"N21",name:"Nozomi 21",kind:"Tōkaidō Shinkansen",from:"Tokyo",to:"Kyoto",depart:"08:00",arrive:"10:15",minutes:135,stops:2,price:14170,platform:"19",accent:"coral"},
  {id:"H505",name:"Hikari 505",kind:"Tōkaidō Shinkansen",from:"Tokyo",to:"Kyoto",depart:"08:33",arrive:"11:11",minutes:158,stops:5,price:13850,platform:"18",accent:"blue"},
  {id:"N25",name:"Nozomi 25",kind:"Tōkaidō Shinkansen",from:"Tokyo",to:"Kyoto",depart:"09:12",arrive:"11:27",minutes:135,stops:2,price:14170,platform:"17",accent:"coral"},
  {id:"K715",name:"Kodama 715",kind:"Tōkaidō Shinkansen",from:"Tokyo",to:"Kyoto",depart:"10:03",arrive:"13:42",minutes:219,stops:12,price:13320,platform:"16",accent:"teal"},
  {id:"N61",name:"Nozomi 61",kind:"Sanyō Shinkansen",from:"Shin-Osaka",to:"Hiroshima",depart:"09:02",arrive:"10:29",minutes:87,stops:2,price:10630,platform:"21",accent:"coral"},
  {id:"S551",name:"Sakura 551",kind:"Sanyō Shinkansen",from:"Shin-Osaka",to:"Hakata",depart:"10:20",arrive:"12:58",minutes:158,stops:7,price:15120,platform:"20",accent:"teal"},
  {id:"H17",name:"Hayabusa 17",kind:"Tōhoku Shinkansen",from:"Tokyo",to:"Sendai",depart:"09:20",arrive:"10:53",minutes:93,stops:1,price:11410,platform:"22",accent:"green"},
  {id:"K509",name:"Kagayaki 509",kind:"Hokuriku Shinkansen",from:"Tokyo",to:"Kanazawa",depart:"10:24",arrive:"12:56",minutes:152,stops:3,price:14380,platform:"23",accent:"gold"},
  {id:"N04",name:"Nozomi 4",kind:"Tōkaidō Shinkansen",from:"Kyoto",to:"Tokyo",depart:"07:45",arrive:"09:58",minutes:133,stops:2,price:14170,platform:"12",accent:"coral"},
  {id:"H522",name:"Hikari 522",kind:"Tōkaidō Shinkansen",from:"Kyoto",to:"Tokyo",depart:"10:08",arrive:"12:48",minutes:160,stops:5,price:13850,platform:"11",accent:"blue"},
  {id:"N110",name:"Nozomi 110",kind:"Tōkaidō Shinkansen",from:"Nagoya",to:"Shin-Osaka",depart:"11:03",arrive:"11:52",minutes:49,stops:1,price:6680,platform:"16",accent:"coral"},
  {id:"N38",name:"Nozomi 38",kind:"Tōkaidō Shinkansen",from:"Kyoto",to:"Shin-Osaka",depart:"13:01",arrive:"13:15",minutes:14,stops:0,price:3000,platform:"13",accent:"coral"}
];
const yen=(n:number)=>"¥"+n.toLocaleString("ja-JP");
const initialDate=()=>{const d=new Date();d.setDate(d.getDate()+1);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")};
const currentDate=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")};
const displayDate=(s:string)=>s.split("-").reverse().join("/");
const duration=(m:number)=>m>=60?`${Math.floor(m/60)} giờ ${m%60} phút`:`${m} phút`;
const nav=[{id:"search",label:"Tìm chuyến tàu",icon:Search},{id:"tickets",label:"Vé của tôi",icon:Ticket},{id:"schedule",label:"Lịch trình tàu",icon:CalendarDays}] as const;
type View=typeof nav[number]["id"];

export default function Home(){
  const [view,setView]=useState<View>("search"),[from,setFrom]=useState("Tokyo"),[to,setTo]=useState("Kyoto"),[date,setDate]=useState(initialDate),[people,setPeople]=useState(1);
  const [criteria,setCriteria]=useState({from:"Tokyo",to:"Kyoto",date:initialDate()}),[sort,setSort]=useState("departure"),[selected,setSelected]=useState<Train|null>(null);
  const [seatClass,setSeatClass]=useState("Ghế thường"),[passengerName,setPassengerName]=useState(""),[email,setEmail]=useState("");
  const [bookings,setBookings]=useState<Booking[]>([]),[cancelCode,setCancelCode]=useState<string|null>(null),[notice,setNotice]=useState(""),[mobileMenu,setMobileMenu]=useState(false),[ready,setReady]=useState(false),[expandedId,setExpandedId]=useState<string|null>(null);
  useEffect(()=>{try{const value=JSON.parse(localStorage.getItem("sakura-rail-bookings")||"[]");if(Array.isArray(value))setBookings(value)}catch{}setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem("sakura-rail-bookings",JSON.stringify(bookings))},[bookings,ready]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),5500);return()=>clearTimeout(timer)},[notice]);
  useEffect(()=>{
    type ToolContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
    const context=(document as Document & {modelContext?:ToolContext}).modelContext;
    if(!context?.registerTool)return;
    const controller=new AbortController();
    try{void Promise.resolve(context.registerTool({name:"search_sample_trains",title:"Tìm tàu mẫu",description:"Tra cứu tuyến tàu mẫu và cập nhật kết quả đang hiển thị.",inputSchema:{type:"object",properties:{from:{type:"string",enum:stations},to:{type:"string",enum:stations}},required:["from","to"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){
      const query=input as {from?:string;to?:string};
      if(!stations.includes(query.from||"")||!stations.includes(query.to||"")||query.from===query.to)throw new Error("Ga đi và ga đến không hợp lệ.");
      setFrom(query.from!);setTo(query.to!);setCriteria({from:query.from!,to:query.to!,date});setView("search");
      return {from:query.from,to:query.to,count:trains.filter(t=>t.from===query.from&&t.to===query.to).length};
    }},{signal:controller.signal})).catch(()=>{})}catch{}
    return()=>controller.abort();
  },[date]);
  const results=useMemo(()=>trains.filter(t=>t.from===criteria.from&&t.to===criteria.to).sort((a,b)=>sort==="price"?a.price-b.price:sort==="duration"?a.minutes-b.minutes:a.depart.localeCompare(b.depart)),[criteria,sort]);
  const activeCount=bookings.filter(b=>b.status==="Đã xác nhận").length;
  function changeView(v:View){setView(v);setMobileMenu(false);setNotice("")}
  function search(e:React.FormEvent){e.preventDefault();if(from===to){setNotice("Ga đi và ga đến cần khác nhau.");return}setCriteria({from,to,date});setExpandedId(null);setNotice("")}
  function chooseRoute(start:string,end:string){setFrom(start);setTo(end);setCriteria({from:start,to:end,date});setExpandedId(null);document.getElementById("results-heading")?.scrollIntoView({behavior:"smooth",block:"start"})}
  function book(e:React.FormEvent){e.preventDefault();if(!selected||!passengerName.trim()||!email.trim())return;
    const code="SR"+Math.random().toString(36).slice(2,8).toUpperCase(),seat=Array.from({length:people},(_,i)=>String(Math.floor(Math.random()*8)+1).padStart(2,"0")+["A","B","C","D","E","F"][i]).join(", ");
    setBookings(prev=>[{code,train:selected,date:criteria.date,passengers:people,seatClass,name:passengerName.trim(),email:email.trim(),seat,status:"Đã xác nhận"},...prev]);
    setSelected(null);setPassengerName("");setEmail("");setView("tickets");setNotice(`Đã tạo vé ${code}. Đây là vé mô phỏng, chưa thanh toán hoặc giữ chỗ với hãng tàu.`);
  }
  return <div className="app-shell">
    <aside className={`sidebar ${mobileMenu?"mobile-open":""}`}><div className="brand"><div className="brand-mark"><TrainFront size={21}/></div><div><strong>SAKURA<span>RAIL</span></strong><small>JAPAN RAIL PLANNER</small></div></div><div className="sidebar-label">KHÁM PHÁ</div>
      <nav aria-label="Điều hướng chính">{nav.map(item=><button key={item.id} className={`nav-item ${view===item.id?"active":""}`} onClick={()=>changeView(item.id)}><item.icon size={19}/><span>{item.label}</span>{item.id==="tickets"&&activeCount>0&&<b>{activeCount}</b>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-note"><span className="note-icon"><Ticket size={17}/></span><strong>Chuyến đi của bạn</strong><p>{activeCount?`${activeCount} vé mô phỏng đang hiệu lực trên thiết bị này.`:"Lưu hành trình sau khi chọn một chuyến tàu."}</p><button onClick={()=>changeView("tickets")}>Xem vé của tôi <ArrowRight size={14}/></button></div><div className="sidebar-foot">Sakura Rail · Giao diện mô phỏng</div></div></aside>
    {mobileMenu&&<button className="mobile-backdrop" aria-label="Đóng menu" onClick={()=>setMobileMenu(false)}/>}
    <main className="main-area"><header className="topbar"><button className="menu-button" aria-label="Mở menu" onClick={()=>setMobileMenu(true)}><Menu size={23}/></button><div className="breadcrumbs"><span>Trang chủ</span><ChevronRight size={15}/><strong>{nav.find(x=>x.id===view)?.label}</strong></div><div className="topbar-right"><span className="demo-tag"><span className="demo-dot"/> BẢN DEMO</span><span className="avatar" aria-label="Sakura Rail">SR</span></div></header>
    <div className="content">
      {view==="search"&&<><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> KHÁM PHÁ NHẬT BẢN BẰNG TÀU</div><h1>Hành trình của bạn bắt đầu tại đây.</h1><p>Tra cứu chuyến Shinkansen, so sánh lịch trình và lưu vé trong vài bước.</p></div><div className="heading-stat"><TrainFront size={20}/><div><strong>{trains.length} chuyến mẫu</strong><span>Trên {new Set(trains.map(t=>t.from+"-"+t.to)).size} tuyến đường</span></div></div></div>
        <form className="search-panel" onSubmit={search}><div className="search-panel-title"><TrainFront size={18}/><strong>Tìm kiếm chuyến tàu</strong><span>Một chiều</span></div><div className="search-grid">
          <div className="field"><label htmlFor="station-from">Ga khởi hành</label><div className="field-control"><MapPin size={20}/><Select value={from} onValueChange={v=>setFrom(v||"Tokyo")}><SelectTrigger id="station-from" aria-label="Ga khởi hành"><SelectValue/></SelectTrigger><SelectContent>{stations.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></div>
          <button className="swap-button" type="button" aria-label="Đổi ga đi và ga đến" onClick={()=>{setFrom(to);setTo(from)}}><ArrowLeftRight size={18}/></button>
          <div className="field"><label htmlFor="station-to">Ga đến</label><div className="field-control"><MapPin size={20}/><Select value={to} onValueChange={v=>setTo(v||"Kyoto")}><SelectTrigger id="station-to" aria-label="Ga đến"><SelectValue/></SelectTrigger><SelectContent>{stations.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></div>
          <div className="field"><label htmlFor="travel-date">Ngày đi</label><div className="field-control date-control"><CalendarDays size={20}/><input id="travel-date" type="date" min={currentDate()} value={date} onChange={e=>setDate(e.target.value)} required/></div></div>
          <div className="field"><label>Số hành khách</label><div className="field-control passengers"><button type="button" aria-label="Giảm số hành khách" disabled={people<=1} onClick={()=>setPeople(p=>p-1)}><Minus size={16}/></button><span>{people} người</span><button type="button" aria-label="Tăng số hành khách" disabled={people>=6} onClick={()=>setPeople(p=>p+1)}><Plus size={16}/></button></div></div>
          <button className="search-button" type="submit"><Search size={18}/> Tìm chuyến</button></div></form>
        <div className="suggested-routes"><span>Tuyến gợi ý</span>{[["Tokyo","Kyoto"],["Shin-Osaka","Hiroshima"],["Tokyo","Sendai"],["Kyoto","Tokyo"]].map(([start,end])=><button key={start+end} onClick={()=>chooseRoute(start,end)} className={criteria.from===start&&criteria.to===end?"picked":""}>{start}<ArrowRight size={13}/>{end}</button>)}</div>
        <div className="section-heading" id="results-heading"><div><span className="section-kicker">CHUYẾN TÀU KHẢ DỤNG</span><h2>{criteria.from} <ArrowRight size={21}/> {criteria.to}</h2><p>{displayDate(criteria.date)} · {results.length} chuyến tàu</p></div><div className="sort-wrap"><span>Sắp xếp:</span><Select value={sort} onValueChange={v=>setSort(v||"departure")}><SelectTrigger aria-label="Sắp xếp chuyến tàu"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="departure">Giờ khởi hành</SelectItem><SelectItem value="price">Giá thấp nhất</SelectItem><SelectItem value="duration">Nhanh nhất</SelectItem></SelectContent></Select></div></div>
        <div className="train-list">{results.length?results.map(train=><article className="train-card" key={train.id}><div className="train-card-main"><div className="train-ident"><span className={`train-icon ${train.accent}`}><TrainFront size={22}/></span><div><h3>{train.name}</h3><span>{train.kind}</span></div></div><div className="journey"><div><strong>{train.depart}</strong><small>{train.from}</small></div><div className="journey-line"><span>{duration(train.minutes)}</span><div className="rail-line"><i/><i/></div><small>{train.stops===0?"Đi thẳng":`${train.stops} điểm dừng`}</small></div><div><strong>{train.arrive}</strong><small>{train.to}</small></div></div><div className="train-price"><small>Giá tham khảo</small><strong>{yen(train.price)}</strong><span>/ hành khách</span></div><button className="book-button" onClick={()=>{setSeatClass("Ghế thường");setSelected(train)}}>Chọn chuyến <ArrowRight size={16}/></button></div><div className="train-card-foot"><span><Clock3 size={14}/> {duration(train.minutes)}</span><span><MapPin size={14}/> Sân ga {train.platform} (mẫu)</span><button aria-expanded={expandedId===train.id} aria-controls={`detail-${train.id}`} onClick={()=>setExpandedId(expandedId===train.id?null:train.id)}>Chi tiết chuyến <ChevronDown size={15}/></button></div>{expandedId===train.id&&<div className="train-detail" id={`detail-${train.id}`}><div><small>MÃ CHUYẾN</small><strong>{train.id}</strong></div><div><small>HÀNH TRÌNH</small><strong>{train.from} → {train.to}</strong></div><div><small>ĐIỂM DỪNG</small><strong>{train.stops===0?"Đi thẳng":`${train.stops} điểm dừng`}</strong></div><div><small>HẠNG GHẾ</small><strong>Thường · Xanh</strong></div><p>Giờ chạy, sân ga và giá vé là ví dụ thiết kế; không dùng để lên tàu thực tế.</p></div>}</article>):<div className="empty-state"><TrainFront size={34}/><h3>Chưa có chuyến phù hợp</h3><p>Dữ liệu mẫu hiện chưa có tuyến {criteria.from} – {criteria.to}. Hãy chọn một tuyến gợi ý ở phía trên.</p></div>}</div>
        <div className="feature-grid"><div className="feature-banner"><img src="/shinkansen.png" alt="Tàu Shinkansen tại sân ga ở Nhật Bản"/><div className="feature-shade"/><div className="feature-text"><span>TRẢI NGHIỆM ĐƯỜNG SẮT NHẬT BẢN</span><h2>Từng chuyến đi,<br/>một góc nhìn mới.</h2><p>Tokyo · Kyoto · Osaka và nhiều điểm đến khác</p></div><span className="banner-index">01 / JAPAN</span></div><div className="tip-card"><div className="tip-symbol"><Info size={20}/></div><span>TRƯỚC KHI KHỞI HÀNH</span><h3>Chuẩn bị cho chuyến tàu</h3><ul><li><Check size={15}/> Kiểm tra lại ngày, giờ và ga khởi hành</li><li><Check size={15}/> Có mặt sớm để tìm đúng sân ga</li><li><Check size={15}/> Đối chiếu vé với lịch chạy chính thức</li></ul><p>Thông tin trên trang là dữ liệu mô phỏng.</p></div></div>
      </>}
      {view==="tickets"&&<><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> YOUR JOURNEYS</div><h1>Vé của tôi</h1><p>Theo dõi những chuyến tàu bạn đã đặt trên thiết bị này.</p></div><button className="outline-action" onClick={()=>changeView("search")}>Tìm chuyến mới <ArrowRight size={16}/></button></div><div className="ticket-stats"><div><span>Tổng lượt đặt</span><strong>{bookings.length}</strong></div><div><span>Vé đang hiệu lực</span><strong>{activeCount}</strong></div><div><span>Đã hủy</span><strong>{bookings.length-activeCount}</strong></div></div>{bookings.length?<div className="ticket-list">{bookings.map(b=><article key={b.code} className={`ticket-card ${b.status==="Đã hủy"?"cancelled":""}`}><div className="ticket-top"><span className="ticket-code"><Ticket size={17}/> {b.code}</span><span className={`status ${b.status==="Đã hủy"?"off":""}`}>{b.status}</span></div><div className="ticket-main"><div><small>{b.train.name} · {b.train.kind}</small><h3>{b.train.from} <ArrowRight size={20}/> {b.train.to}</h3><p><CalendarDays size={15}/> {displayDate(b.date)} <span>·</span> {b.train.depart} – {b.train.arrive}</p></div><strong>{yen((b.train.price+(b.seatClass==="Ghế xanh"?5200:0))*b.passengers)}</strong></div><div className="ticket-footer"><span>{b.name} · {b.passengers} hành khách · {b.seatClass} · Ghế {b.seat}</span>{b.status==="Đã xác nhận"&&<button onClick={()=>setCancelCode(b.code)}>Hủy vé</button>}</div></article>)}</div>:<div className="empty-state large"><Ticket size={38}/><h3>Chưa có vé nào</h3><p>Chọn một chuyến tàu để bắt đầu hành trình của bạn.</p><button className="book-button" onClick={()=>changeView("search")}>Tìm chuyến tàu <ArrowRight size={16}/></button></div>}</>}
      {view==="schedule"&&<><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> TIMETABLE</div><h1>Lịch trình tàu</h1><p>Tham khảo các tuyến và giờ chạy trong dữ liệu mẫu.</p></div></div><div className="schedule-info"><Clock3 size={20}/><p>Lịch trình và giá vé bên dưới chỉ để minh họa giao diện. Hãy kiểm tra thông tin chính thức của hãng tàu trước khi di chuyển.</p></div><div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th>Tàu</th><th>Tuyến</th><th>Khởi hành</th><th>Đến nơi</th><th>Thời gian</th><th>Giá tham khảo</th></tr></thead><tbody>{trains.map(t=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.kind}</small></td><td>{t.from} <ArrowRight size={14}/> {t.to}</td><td><strong>{t.depart}</strong><small>Sân ga {t.platform}</small></td><td><strong>{t.arrive}</strong></td><td>{duration(t.minutes)}</td><td className="table-price">{yen(t.price)}</td></tr>)}</tbody></table></div></>}
      <footer className="footer"><span>© Sakura Rail 2026</span><span>Ứng dụng React minh họa · Không bán vé thật</span></footer>
    </div></main>
    <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="booking-modal"><DialogHeader><DialogTitle>Thông tin đặt vé</DialogTitle><DialogDescription>Kiểm tra hành trình và nhập thông tin hành khách.</DialogDescription></DialogHeader>{selected&&<form onSubmit={book}><div className="modal-route"><span>{selected.from}</span><ArrowRight size={18}/><span>{selected.to}</span></div><div className="modal-meta"><span><CalendarDays size={15}/> {displayDate(criteria.date)}</span><span><Clock3 size={15}/> {selected.depart} – {selected.arrive}</span><span><TrainFront size={15}/> {selected.name}</span></div><div className="modal-divider"/><label className="form-label">Hạng ghế</label><div className="class-grid">{["Ghế thường","Ghế xanh"].map((c,i)=><button type="button" className={`class-option ${seatClass===c?"chosen":""}`} key={c} onClick={()=>setSeatClass(c)}><span>{c}</span><strong>{yen(selected.price+(i?5200:0))}</strong><small>/ người</small></button>)}</div><div className="form-grid"><label className="form-label">Họ và tên hành khách<input required maxLength={80} value={passengerName} onChange={e=>setPassengerName(e.target.value)} placeholder="Nguyễn Văn A"/></label><label className="form-label">Email liên hệ<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com"/></label></div><div className="modal-total"><span>Tổng cộng <small>({people} hành khách)</small></span><strong>{yen((selected.price+(seatClass==="Ghế xanh"?5200:0))*people)}</strong></div><p className="simulation-note"><CreditCard size={15}/> Đặt vé mô phỏng. Không phát sinh thanh toán hoặc giữ chỗ thật.</p><button className="confirm-button" type="submit">Xác nhận đặt vé <ArrowRight size={17}/></button></form>}</DialogContent></Dialog>
    <AlertDialog open={!!cancelCode} onOpenChange={open=>{if(!open)setCancelCode(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Hủy vé này?</AlertDialogTitle><AlertDialogDescription>Vé mô phỏng sẽ chuyển sang trạng thái đã hủy và vẫn hiển thị trong lịch sử.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Giữ vé</AlertDialogCancel><AlertDialogAction onClick={()=>{setBookings(prev=>prev.map(b=>b.code===cancelCode?{...b,status:"Đã hủy"}:b));setCancelCode(null);setNotice("Đã hủy vé mô phỏng.")}}>Hủy vé</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    {notice&&<div className="toast" role="status"><Check size={18}/><span>{notice}</span><button aria-label="Đóng thông báo" onClick={()=>setNotice("")}><X size={16}/></button></div>}
  </div>
}
